spring:
  config:
    import: optional:file:.env[.properties]
  profiles:
    include: oauth, jwt, docker
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}

server:
  port: 8443
  ssl:
    enabled: true
    key-store: src/main/resources/transcall.p12
    key-store-password: ${KEY_STORE_PASSWORD}
    key-store-type: PKCS12
    key-alias: ${KEY_STORE_ALIAS}

# 필요시 로그 레벨 설정 (개발 중 debug)
logging:
  level:
    org.springframework.security: INFO
    io.jsonwebtoken: DEBUG
