spring:
  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 20250714
    url: jdbc:postgresql://localhost:5432/${DB_NAME}
    user: ${DB_USER}
    password: ${DB_PASSWORD}
    locations: classpath:db/migration
